import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { TeamsProvider } from "./contexts/TeamsContext";

const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "OP Team Database",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <TeamsProvider>{children}</TeamsProvider>
      </body>
    </html>
  );
}
